baseurl: ""
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-redirect-from
  - jekyll-menus
  - liquid-md5
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - favicon.json
  - faviconData.json
  - package.json
  - yarn.lock
  - README.md
  - '*.orig'
  - '*.json'

permalink: /blog/:categories/:title/
categories: [ hire, graduate, landing ]

form_url: "https://4runw89p71.execute-api.us-west-1.amazonaws.com/latest/hubspot"
hubspot_portal_id: 4009818

key: austin
url: "https://austincodingacademy.com"
phone: (512) 827-8498
acronym: aca
head_title: 'Austin Coding Academy | Learn to Code, Change Your Life'
google_tag_manager: GTM-TBH7GK
google_tag_manager_amp: GTM-KZ9XHND
contact_form_guid: 33cc0e23-1881-4874-a1d0-2c0307f20e41
application_form_guid: 9d476e09-2737-4394-b7db-f0395a2d26d5
course_guide_form_guid: 702969c4-4c75-4b99-b6d2-59d04d6ebd03
corporate_form_guid: b8fb52b4-28de-4133-920b-7f587724bb3d
corporate_trainings_form_guid: a000aab9-9870-4578-a496-2649ea46fb7e
twitter: '@AustinCoding'
filters: true
locations:
  - address: Downtown
    street: 701 Brazos St, Ste 1616
    locality: Austin, TX 78701
    url: https://www.google.com/maps/place/Austin+Coding+Academy/@30.2688755,-97.7427528,17z/data=!3m1!4b1!4m5!3m4!1s0x8644b4e31ad087bd:0xd6644ce54fe2531c!8m2!3d30.2688755!4d-97.7405641
  - address: North Austin
    street: 314 E Highland Mall Blvd, Ste 114
    locality: Austin, TX 78752
    url: https://www.google.com/maps/place/North+Austin+Coding+Academy/@30.3290949,-97.7136072,17z/data=!3m1!4b1!4m5!3m4!1s0x8644cba00a32dc3d:0x8807e75b730c450f!8m2!3d30.3290949!4d-97.7114185

