url: "https://lubbockcodingacademy.com"
phone: (806) 905-5021
key: lubbock
acronym: lca
locations:
  - address: South Plain College Lubbock Center,<br>3907 Avenue Q, Lubbock,<br>TX 79412
    street: 3907 Avenue Q
    locality: Lubbock, TX 79412
    url: https://www.google.com/maps/place/South+Plains+College+Lubbock+Center/@33.5577634,-101.8559531,17z/data=!3m1!4b1!4m5!3m4!1s0x86fe6d1839084583:0x8bdaa2a3477f2bc8!8m2!3d33.5577634!4d-101.8537644
