version: 2
jobs:
  build:
    docker:
      - image: circleci/ruby:2.5.1-node-browsers

    working_directory: ~/repo

    steps:
      - checkout

      - restore_cache:
          keys:
            - v1-gem-cache-{{ arch }}-{{ .Branch }}-{{ checksum "Gemfile.lock" }}
            - v1-gem-cache-{{ arch }}-{{ .Branch }}-
            - v1-gem-cache-{{ arch }}-
      - run: bundle install --path ~/.bundle && bundle clean
      - save_cache:
          paths:
            - ~/.bundle
          key: v1-gem-cache-{{ arch }}-{{ .Branch }}-{{ checksum "Gemfile.lock" }}

      - restore_cache:
          keys:
            - yarn-packages-v1-{{ .Branch }}-{{ checksum "yarn.lock" }}
            - yarn-packages-v1-{{ .Branch }}-
            - yarn-packages-v1-
      - run: yarn install --frozen-lockfile
      - save_cache:
          paths:
            - node_modules
          key: yarn-packages-v1-{{ .Branch }}-{{ checksum "yarn.lock" }}

      - run: yarn test
      - run: node events.js
      - run: node tutoring.js
      - deploy:
          name: Deploy
          command: |
              if [ "${CIRCLE_BRANCH}" == "preview" ]; then
              git config --global user.email "kevin@austincodingacademy.com"
              git config --global user.name "Kevin Colten"
              yarn deploy
              yarn preview
              fi
              if [ "${CIRCLE_BRANCH}" == "master" ]; then
              git config --global user.email "kevin@austincodingacademy.com"
              git config --global user.name "Kevin Colten"
              yarn sitemap
              yarn deploy
              sudo apt install rsync
              rsync -a --delete -e "ssh -o StrictHostKeyChecking=no" _site/ root@134.209.57.190:/usr/share/nginx/html
              fi

workflows:
  version: 2
  commit:
    jobs:
     - build:
        filters:
          branches:
            ignore: gh-pages
  hourly:
    triggers:
      - schedule:
          cron: "0 * * * *"
          filters:
            branches:
              only:
                - master
    jobs:
      - build
